// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package xdp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadXspa returns the embedded CollectionSpec for Xspa.
func LoadXspa() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XspaBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Xspa: %w", err)
	}

	return spec, err
}

// LoadXspaObjects loads Xspa and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*XspaObjects
//	*XspaPrograms
//	*XspaMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadXspaObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadXspa()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// XspaSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XspaSpecs struct {
	XspaProgramSpecs
	XspaMapSpecs
	XspaVariableSpecs
}

// XspaProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XspaProgramSpecs struct {
	XspaMain *ebpf.ProgramSpec `ebpf:"xspa_main"`
}

// XspaMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XspaMapSpecs struct {
	SeenNonces   *ebpf.MapSpec `ebpf:"seen_nonces"`
	SpaRingbuf   *ebpf.MapSpec `ebpf:"spa_ringbuf"`
	WhitelistLru *ebpf.MapSpec `ebpf:"whitelist_lru"`
}

// XspaVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XspaVariableSpecs struct {
	SIPHASH_KEYS *ebpf.VariableSpec `ebpf:"SIPHASH_KEYS"`
	SPA_PORT     *ebpf.VariableSpec `ebpf:"SPA_PORT"`
}

// XspaObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadXspaObjects or ebpf.CollectionSpec.LoadAndAssign.
type XspaObjects struct {
	XspaPrograms
	XspaMaps
	XspaVariables
}

func (o *XspaObjects) Close() error {
	return _XspaClose(
		&o.XspaPrograms,
		&o.XspaMaps,
	)
}

// XspaMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadXspaObjects or ebpf.CollectionSpec.LoadAndAssign.
type XspaMaps struct {
	SeenNonces   *ebpf.Map `ebpf:"seen_nonces"`
	SpaRingbuf   *ebpf.Map `ebpf:"spa_ringbuf"`
	WhitelistLru *ebpf.Map `ebpf:"whitelist_lru"`
}

func (m *XspaMaps) Close() error {
	return _XspaClose(
		m.SeenNonces,
		m.SpaRingbuf,
		m.WhitelistLru,
	)
}

// XspaVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadXspaObjects or ebpf.CollectionSpec.LoadAndAssign.
type XspaVariables struct {
	SIPHASH_KEYS *ebpf.Variable `ebpf:"SIPHASH_KEYS"`
	SPA_PORT     *ebpf.Variable `ebpf:"SPA_PORT"`
}

// XspaPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadXspaObjects or ebpf.CollectionSpec.LoadAndAssign.
type XspaPrograms struct {
	XspaMain *ebpf.Program `ebpf:"xspa_main"`
}

func (p *XspaPrograms) Close() error {
	return _XspaClose(
		p.XspaMain,
	)
}

func _XspaClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xspa_bpfel.o
var _XspaBytes []byte
